#!/bin/bash

set -e
set -o pipefail
set -E

if [ "$DEBUG" = "true" ]; then
  set -x
fi

echo "$(date +%x\ %H:%M:%S) [START] Incremental deploy"

# Import basic functions
source lib/helpers.sh
source lib/init.sh

# Sync the terrafrom state
echo "$(date +%x\ %H:%M:%S) [START] Check that current status is consistent"
QUANTITY_CURRENT=$(get_current_quantity)
export QUANTITY_CURRENT
source lib/sync.sh
echo "$(date +%x\ %H:%M:%S) [END] Check that current status is consistent"

# Notify that the deploy is starting
curl -sS -X PUT http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/start -d "{ \"group\": \"${IDENTITY}\", \"number\": \"${QUANTITY}\", \"time\": \"$(date +%s)\" }" > /dev/null
curl -sS -X DELETE http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/start > /dev/null
curl -sS -X PUT http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/ongoing -d "{ \"group\": \"${IDENTITY}\", \"number\": \"${QUANTITY}\", \"time\": \"$(date +%s)\" }" > /dev/null

while [ ${QUANTITY_CURRENT} -ne ${QUANTITY} ]; do

  # The instance are increasing
  if [ $QUANTITY_CURRENT -lt $QUANTITY ]; then
    QUANTITY_CURRENT=$(echo "$QUANTITY_CURRENT + 1" | bc)
    export QUANTITY_CURRENT
  fi

  # The instance are decreasing
  if [ $QUANTITY_CURRENT -gt $QUANTITY ]; then
    QUANTITY_CURRENT=$(echo "$QUANTITY_CURRENT - 1" | bc)
    export QUANTITY_CURRENT
  fi

  source lib/sync.sh

done

# Notify that the deploy is ended
curl -sS -X DELETE http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/ongoing > /dev/null
curl -sS -X PUT http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/end -d "{ \"group\": \"${IDENTITY}\", \"number\": \"${QUANTITY}\", \"time\": \"$(date +%s)\" }" > /dev/null
curl -sS -X DELETE http://${CONSUL}:${CONSUL_PORT}/v1/kv/${CLUSTER_NAME}/deploy/end > /dev/null
echo "$(date +%x\ %H:%M:%S) [END] Incremental deploy"
