#!/bin/bash

set -e
set -o pipefail
set -E

if [ "$DEBUG" = "true" ]; then
  set -x
fi

# Cleanup sequentially
source deploy

# Import basic functions
source lib/helpers.sh
source lib/init.sh

source lib/destroy.sh
